### ISSUE TITLE
display positions

### ISSUE THREAD

**Issue by antimodular** [motoishmz/ofxDisplayLayout#1]
nice addon. looks very promising.

i am trying to figure out how to make it remember and arrange also the position of each display in the case when the displays are not just horizontally aligned.
any tips?
thanks.

**Comment by motoishmz** [comment]
Hey thanks for your comment. For the quick answer, you can put the position of each display manually by editing around here: https://github.com/motoishmz/ofxDisplayLayout/blob/master/src/ofxDisplayLayout.mm#L251

The size of `vector<Display> displays` should be the number of displays you connect to your MacOS - if you use not MacPro but MacBook, don't forget counting the built-in display. The position of the primary display should be `ofPoint::zero()`, and you can put the position of non-primary displays manually. 

It's nice if the position of each display could be loaded from Json or something, but I don't have the example like that.

Thanks!

**Comment by antimodular** [comment]
thanks.
i figured most of it out and posted a pull request to your branch

**Comment by motoishmz** [comment]
Cool, thanks. I didn't receive any PR from you, could you send me a PR again? https://github.com/antimodular/ofxDisplayLayout/commit/8ba2dcbf5a4c31d08b359cd05981bb615a95b00e
